apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      serviceAccountName: clo835-group3  # Assign the created ServiceAccount
      # volumes:  # Define a volume for the PVC
      #   - name: mysql-storage
      #     persistentVolumeClaim:
      #       claimName: mysql-pvc
      containers:
      - name: mysql-db
        image: 897193292353.dkr.ecr.us-east-1.amazonaws.com/db:dbIMG
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-database
       
        ports:
        - containerPort: 3306
          protocol: TCP
        # volumeMounts:  # Mount the PVC volume to the container
        # - name: mysql-storage
        #   mountPath: /var/lib/mysql  # Adjust this path according to your MySQL configuration
