apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      containers:
      - name: mysql-db
        image: 897193292353.dkr.ecr.us-east-1.amazonaws.com/db:mysqlIMG
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass123
          - name: MYSQL_DATABASE
            value: employees
        ports:
        - containerPort: 3306
          protocol: TCP
